'use strict';

export const ENTITY_ADD = 'ENTITY_ADD';
export const ENTITY_REMOVE = 'ENTITY_REMOVE';
export const ENTITY_CREATE = 'ENTITY_CREATE';
export const ENTITY_DELETE = 'ENTITY_DELETE';
export const ENTITY_SET_ROOT = 'ENTITY_SET_ROOT';

export const ADD_COMPONENT_LIGHT = 'ADD_COMPONENT_LIGHT';
export const REMOVE_COMPONENT_LIGHT = 'REMOVE_COMPONENT_LIGHT';
export const LIGHT_TERN_OFF = 'LIGHT_TERN_OFF';
export const LIGHT_TERN_ON = 'LIGHT_TERN_ON';

export const ADD_COMPONENT_ROTATOR = 'ADD_COMPONENT_ROTATOR';
export const REMOVE_COMPONENT_ROTATOR = 'REMOVE_COMPONENT_ROTATOR';

export const SCENE__SET_CAMERA = 'SCENE__SET_CAMERA';
